EASinventorysystem/EASinventorysystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inventoryapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EASinventorysystem/inventoryapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.account_login, name='account_login'),
    path('account_logout/', views.account_logout, name='account_logout'),
    path('current_inventory', views.inventory_list, name='current_inventory'),
    path('add_product', views.add_product, name='add_product'),
    path('view_product/<int:product_pk>/', views.view_product, name='view_product'),
    path('update_product/<int:pk>/', views.update_product, name='update_product'),
    path('current_pos', views.purchase_order_list, name='current_pos'),
    # path('add_po', views.add_purchase_order, name='add_po'),
    # path('add_po_second', views.add_po_second, name='add_po_second'), 
    path('add_po_direct_customer', views.add_purchase_order_direct_customer, name='add_po_direct_customer'),
    path('add_po_consignee', views.add_purchase_order_consignee, name='add_po_consignee'),

    path('update_po_direct_customer/<int:po_pk>/<int:c_pk>/', views.update_PO_direct_customer, name='update_po_direct_customer'),
    path('update_po_consignee/<int:po_pk>/<int:c_pk>/', views.update_PO_consignee, name='update_po_consignee'),
    
    path('history_po', views.history_PO, name='history_po'),
    path('view_po_history/<int:pk>/', views.view_po_history, name='view_po_history'), 

    path('history_pro', views.history_PRO, name='history_pro'),
    path('view_pro_history/<int:pk>/', views.view_pro_history, name='view_pro_history'), 
    
    path('current_pros', views.requisition_order_list, name='current_pros'),
    path('view_po/<int:pk>/', views.view_po, name='view_po'), 

    path('update_PO_progress/<int:PO_pk>/', views.update_PO_progress, name='update_PO_progress'), 
    path('update_PRO_progress/<int:PRO_pk>/', views.update_PRO_progress, name='update_PRO_progress'), 
    
    path('close_po/<int:pk>/<int:account_id>/', views.close_po, name='close_po'),
    path('close_pro/<int:pk>/<int:account_id>/', views.close_pro, name='close_pro'),
    path('cancel_po/<int:pk>/<int:account_id>/', views.cancel_po, name='cancel_po'),
    path('cancel_pro/<int:pk>/<int:account_id>/', views.cancel_pro, name='cancel_pro'),
    path('cancel_po_specific/<int:pk>/<int:account_id>/', views.cancel_po_specific, name='cancel_po_specific'),
    path('cancel_pro_specific/<int:pk>/<int:account_id>/', views.cancel_pro_specific, name='cancel_pro_specific'),
    path('add_pro', views.add_requisition_order, name='add_pro'),
    path('view_pro/<int:pk>/', views.view_pro, name='view_pro'), 
    path('update_pro/<int:pk>/', views.update_pro, name='update_pro'),

    path('current_customers', views.customer_list, name='current_customers'),
    
    
    path('create_direct_customer', views.create_direct_customer, name='create_direct_customer'),
    path('create_consignee', views.create_consignee, name='create_consignee'),
    path('view_customer/<str:customer_type>/<int:customer_id>/', views.view_customer, name='view_customer'),
    path('update_direct_customer/<int:pk>/', views.update_direct_customer, name='update_direct_customer'),
    path('update_consignee/<int:pk>/', views.update_consignee, name='update_consignee'),

    path('categories_consignee_tags', views.categories_consignee_tags, name='categories_consignee_tags'),
    path('add_category', views.add_category, name='add_category'),
    path('view_category/<int:category_id>/', views.view_category, name='view_category'),

    path('generate_inventory_summary', views.generate_inventory_summary, name='generate_inventory_summary'),
    path('view_category_details/<int:category_id>/', views.view_category_details, name='view_category_details'),
    path('view_consignee_details/<int:consignee_id>/', views.view_consignee_tag_details, name='view_consignee_details'),
    path('create__consignee', views.create__consignee, name='create__consignee'),
    
    path('update_category/<int:pk>/', views.update_category, name='update_category'),
    path('update_tags/<int:pk>/', views.update_tags, name='update_tags'),

    path('my_account', views.my_account, name='my_account'),
    path('employee_accounts', views.employee_accounts, name='employee_accounts'),
    path('edit_my_account', views.edit_my_account, name='edit_my_account'),
    path('add_new_employee', views.add_new_employee, name='add_new_employee'),
    path('view_employee/<int:pk>/', views.view_employee, name='view_employee'),
    path('update_employee/<int:pk>/', views.update_employee, name='update_employee'),
    path('hide_account/<int:pk>/', views.hide_account, name='hide_account'),
    path('unhide_account/<int:pk>/', views.unhide_account, name='unhide_account'),


    path('generate_inventory_summary_screen', views.generate_inventory_summary_screen, name='generate_inventory_summary_screen'),

    path('edit_count', views.edit_count, name='edit_count'),
    path('inventory_update_history', views.inventory_update_history, name='inventory_update_history'),
    path('partially_fulfill/<int:pk>/', views.partially_fulfill, name='partially_fulfill'),
    path('history_partially_fulfilled/', views.history_partially_fulfilled, name='history_partially_fulfilled'),

    path('view_partially_fulfilled/<int:pk>/', views.view_partially_fulfilled, name='view_partially_fulfilled'),
    path('view_edit_count/<int:pk>/', views.view_edit_count, name='view_edit_count'),

    
]

EASinventorysystem/inventoryapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxLengthValidator, MaxValueValidator
from django.contrib.auth.models import User


# Create your models here.
# will figure out how to make the images into their own folders
class Account(models.Model):
    Account_ID = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Profile_Picture = models.ImageField(upload_to='account_pfps/', null=True, blank=True)
    First_Name = models.CharField(max_length=32)
    Last_Name = models.CharField(max_length=32)
    Role = models.CharField(max_length = 32)
    Visibility = models.BooleanField(default=True)

    def getUsername(self):
        return self.Username
    
    def getPassword(self):
        return self.Password
    
    def __str__(self):
        return str(self.user)

class Product(models.Model):
    Product_ID = models.AutoField(primary_key=True)            
    EAS_Product_ID = models.CharField(max_length=32, unique=True)
    Name = models.CharField(max_length=64)
    Picture = models.ImageField(null=True, blank=True, upload_to='product_images/', )
    SKU = models.CharField(max_length=32)
    Price = models.DecimalField(max_digits=7, decimal_places=2, validators=[MinValueValidator(0)])
    Actual_Inventory_Count = models.PositiveIntegerField(validators =[MaxValueValidator(99999)])
    Reserved_Inventory_Count = models.PositiveIntegerField(validators =[MaxValueValidator(99999)], default = 0)
    To_Be_Received_Inventory_Count = models.PositiveIntegerField(validators =[MaxValueValidator(99999)], default = 0)
    Visibility = models.BooleanField(default=True)
    Product_Low_Stock_Threshold = models.PositiveIntegerField(validators =[MaxValueValidator(99999)], null=True, blank=True)
    Product_Stock_Status = models.CharField(max_length=16) 
    Category = models.ForeignKey("Category", on_delete=models.PROTECT)

    def __str__(self):
        return self.Name

class Category(models.Model):
    Category_ID = models.AutoField(primary_key=True)
    Category_Name = models.CharField(max_length=32, unique=True)
    Category_Hex_Color_ID = models.CharField(max_length=7, unique=True)
    Description = models.TextField(validators =[MaxLengthValidator(1024)])
    Category_Product_Low_Stock_Threshold = models.PositiveIntegerField(validators =[MaxValueValidator(99999)])
    Notes = models.TextField(validators =[MaxLengthValidator(1024)], null=True, blank=True)

    def __str__(self):
        return self.Category_Name
    
class Purchase_Order(models.Model):
    Purchase_Order_ID = models.AutoField(primary_key=True)
    Creation_Date = models.DateTimeField()
    Requested_Date = models.DateField()
    Fulfilled_Date = models.DateTimeField(null=True, blank=True)
    Total_Due = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0)])
    Notes = models.TextField(validators =[MaxLengthValidator(1024)], null=True, blank=True)
    Progress = models.CharField(max_length=16, default = "Pending")
    PO_Status = models.CharField(max_length=16, default = "Unfulfilled")
    Shipping_Method = models.CharField(max_length=32)
    Order_Method = models.CharField(max_length=32,  null=True, blank=True)
    Customer_ID = models.ForeignKey('Customer', on_delete=models.PROTECT, null=True, blank=True) #null if it is a consignee
    Consignee_ID = models.ForeignKey('Consignee', on_delete=models.PROTECT, null=True, blank=True) #null if it is a customer
    Account_ID_Closed_by = models.ForeignKey('Account', on_delete=models.CASCADE, related_name='po_closed', null=True, blank=True)
    Account_ID_Created_by = models.ForeignKey('Account', on_delete=models.CASCADE, related_name='po_created')
    
    def __str__(self):
        return f" Purchase Order # {self.Purchase_Order_ID}"

class Product_Ordered(models.Model):
    Product_ID = models.ForeignKey(Product, on_delete=models.PROTECT)
    Purchase_Order_ID = models.ForeignKey(Purchase_Order, on_delete=models.PROTECT)
    Quantity = models.PositiveIntegerField( validators=[MaxValueValidator(99999)])

    def __str__(self):
        return f"{self.Product_ID.Name} in {self.Purchase_Order_ID} "
    
class Product_Requisition_Order(models.Model):
    Product_Requisition_ID = models.AutoField(primary_key=True)
    Creation_Date = models.DateTimeField()
    Estimated_Receiving_Date = models.DateField()
    Received_Date = models.DateTimeField(null=True, blank=True)
    PRO_Manufacturer = models.CharField(max_length=32)
    Total_Cost = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0)])
    Notes = models.TextField(validators =[MaxLengthValidator(1024)], null=True, blank=True)
    Progress = models.CharField(max_length=16, default = "Pending")
    PRO_Status = models.CharField(max_length=16, default = "Ongoing")
    Account_ID_Closed_by = models.ForeignKey('Account', on_delete=models.CASCADE, related_name='pro_closed', null=True, blank=True)
    Account_ID_Created_by = models.ForeignKey('Account', on_delete=models.CASCADE, related_name='pro_created')
    
    def __str__(self):
        return f" Product Requisition Order # {self.Product_Requisition_ID}"
    
class Stock_Ordered(models.Model):
    Product_ID = models.ForeignKey(Product, on_delete=models.PROTECT)
    Product_Requisition_ID = models.ForeignKey(Product_Requisition_Order, on_delete=models.PROTECT)
    Quantity = models.PositiveIntegerField( validators=[MaxValueValidator(99999)])
    
    def __str__(self):
        return f"{self.Product_ID.Name} in {self.Product_Requisition_ID} "

class Customer(models.Model):
    Customer_ID = models.AutoField(primary_key=True)
    Customer_Name = models.CharField(max_length=32)
    Address_Line_1 = models.CharField(max_length=128)
    Barangay = models.CharField(max_length=64)
    Municipality = models.CharField(max_length=64)
    Province = models.CharField(max_length=64)
    Zip_Code = models.CharField(max_length=4)
    Primary_Contact_Number = models.CharField(max_length=11)
    Customer_Type = models.CharField(max_length=16)
    Notes = models.TextField(null=True, blank=True, validators=[MaxLengthValidator(1024)])

    def __str__(self):
        return self.Customer_Name
    
class Consignee(models.Model):
    Consignee_ID = models.AutoField(primary_key=True)
    Consignee_Tag_ID = models.CharField(max_length=32, unique=True)
    Consignee_Name = models.CharField(max_length=32, unique=True)
    Address_Line_1 = models.CharField(max_length=128)
    Barangay = models.CharField(max_length=64)
    Municipality = models.CharField(max_length=64)
    Province = models.CharField(max_length=64)
    Zip_Code = models.CharField(max_length=4)
    Primary_Contact_Number = models.CharField(max_length=11)
    Customer_Type = models.CharField(max_length=16)
    Notes = models.TextField(null=True, blank=True, validators=[MaxLengthValidator(1024)])
    Consignment_Period_Start = models.DateField()
    Consignment_Period_End = models.DateField()
    Emergency_Contact_Number = models.CharField(max_length=11,null=True, blank=True)
    Email_Address = models.EmailField(max_length=128)
    Tag_Hex_Color_ID = models.CharField(max_length=7, unique=True)

    def __str__(self):
        return self.Consignee_Name
    
class Consignee_Product(models.Model):
    Product_ID = models.ForeignKey(Product, on_delete=models.PROTECT)
    Consignee_ID = models.ForeignKey(Consignee, on_delete=models.PROTECT)
    
    def getConsignee_Tag(self):
        return self.Consignee_ID.Consignee_Tag_ID
    
    def __str__(self):
        return f"{self.Product_ID.Name} Consignee: {self.Consignee_ID.Consignee_Tag_ID}"

class Count_Edit_History(models.Model):
    Count_Edit_ID = models.AutoField(primary_key=True)
    Date_Updated = models.DateTimeField()
    Initial_Inventory_Count = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])
    Updated_Inventory_Count = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])
    Image_Report = models.ImageField(upload_to='count_edit_images/', null=True, blank=True)
    Text_Report = models.TextField(validators=[MaxLengthValidator(1024)])
    Product_ID = models.ForeignKey(Product, on_delete=models.PROTECT)
    Account_ID = models.ForeignKey(Account, on_delete=models.PROTECT)
    
    def __str__(self):
        return f"Count Edit #{self.Count_Edit_ID} Product: {self.Product_ID}"

class Partially_Fulfilled_History(models.Model):
    Partially_Fulfill_Edit_ID = models.AutoField(primary_key=True)
    Date_Updated = models.DateTimeField()
    Partially_Fulfilled_Quantity = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])
    Image_Report = models.ImageField(upload_to='partially_fulfilled_images/', null=True, blank=True)
    Text_Report = models.TextField(validators =[MaxLengthValidator(1024)])
    Stock = models.ForeignKey(Stock_Ordered, on_delete=models.PROTECT)
    Account_ID = models.ForeignKey(Account, on_delete=models.PROTECT)
    
    def __str__(self):
        return f" Partial fulfill #{self.Partially_Fulfill_Edit_ID} for {self.Stock}"

EASinventorysystem/inventoryapp/templates/inventoryapp/CatsAndTags.html
{% extends 'inventoryapp/base.html' %}
{% load static %}

{% block title %}
    <title>Categories and Tags</title>
{% endblock %}

{% block content %}
<div class="container-fluid">

  <div class="row p-1" style="background-color: #eee;">
    <div class="col-md-auto d-flex align-items-center">
      <h4 class="m-0 mr-3">Categories and Tags</h4>
    </div>
  </div>

  <!-- Buttons row -->
  <div class="row mt-3">
    <!-- Buttons column -->
    <div class="col-md-auto">
      <!-- Create New Category Button -->
      <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#addCategoryModal">Create New Category</button>
    </div>
    <div class="col-md-auto">
      <!-- Create New Tag Button -->
      <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#addTagModal">Create New Tag</button>
    </div>
  </div>

  <!-- Table Categories and Tags row -->
  <div class="row mt-3">
    <!-- Categories Column -->
    <div class="col-md-6">
      <div class="table-responsive">
        <table id="currentCategories" class="table text-center">
          <thead>
            <tr>
              <th scope="col" style="background-color: #C2C1C1; text-align: center;">Category Name</th>
              <th scope="col" style="background-color: #C2C1C1; text-align: center;">Description</th>
              <th scope="col" style="background-color: #C2C1C1;" data-orderable="false"></th>
            </tr>
          </thead>
          <tbody>
            <!-- Iterate over categories and display them -->
            {% for category in categories %}
              <tr>
                <td style="text-align: center;">{{ category.Category_Name }}</td>
                <td style="text-align: center;">{{ category.Description }}</td>
                <td>
                  <!-- Add any additional actions here if needed -->
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <!-- Tags Column -->
    <div class="col-md-6">
      <div class="table-responsive">
        <table id="currentTags" class="table text-center">
          <thead>
            <tr>
              <th scope="col" style="background-color: #C2C1C1; text-align: center;">Tag Name</th>
              <th scope="col" style="background-color: #C2C1C1; text-align: center;">Color</th>
              <th scope="col" style="background-color: #C2C1C1;" data-orderable="false"></th>
            </tr>
          </thead>
          <tbody>
            <!-- Iterate over consignees and display their associated tags -->
            {% for consignee in consignees %}
                <tr>
                  <td style="text-align: center;"><span class="badge" id="badge-{{ forloop.counter }}">{{ consignee.Consignee_Name }}</span></td>
                  <td style="text-align: center;">{{ consignee.Tag_Hex_Color_ID }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.0/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.0/js/dataTables.bootstrap5.js"></script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    // Get all badge elements
    var badges = document.querySelectorAll('.badge');
    
    // Loop through each badge element
    badges.forEach(function(badge, index) {
      // Get the corresponding hex color
      var hexColor = badge.parentElement.nextElementSibling.textContent;
      
      // Set the background color of the badge
      badge.style.backgroundColor = hexColor;
      
      // Check if the background color is light
      if (isColorLight(hexColor)) {
        badge.style.color = '#000000'; // Set text color to black
      } else {
        badge.style.color = '#ffffff'; // Set text color to white
      }

      // Add a black outline to the badge
      badge.style.border = '1px solid #000000';
    });

    // Function to check if a color is light
    function isColorLight(color) {
      // Convert hex color to RGB
      var r = parseInt(color.substr(1, 2), 16);
      var g = parseInt(color.substr(3, 2), 16);
      var b = parseInt(color.substr(5, 2), 16);
      
      // Calculate luminance
      var luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
      
      // Check if luminance is greater than 0.5 (light color)
      return luminance > 0.5;
    }
  });
</script>


</body> 
{% endblock %}

EASinventorysystem/inventoryapp/templates/inventoryapp/edit_my_account.html
{% extends 'inventoryapp/base.html' %}
{% load static %}

{% block content %}

<head>
  <title>My Account</title>
  <style>
    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh; 
    }
    .card {
      width: 50%; 
      margin: 0 auto; 
      padding: 20px;
      background-color: #eee;
      border: none;
      border-radius: 5px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    .image-column {
      display: flex;
      justify-content: center;
    }
    .image-column img {
      width: 50px;
      height: auto; 
    }
    .row {
      margin-bottom: 15px; 
    }
    
    input[type="text"],
    input[type="password"] {
      border: 1px solid #ccc; 
      border-radius: 5px; 
      padding: 8px; 
      background-color: white; 
      width: 100%; 
    }

    .btn-edit {
      font-size: 18px; 
      padding: 6px 28px; 
    }

    .invalid-input {
      border: 1px solid red !important;
    }
  </style>
</head>
<body class="bg-light">
  <div class="container-fluid">
      <div class="row p-1" style="background-color: #eee;">
        <div class="col-md-auto d-flex align-items-center">
          <h4 class="m-0 mr-3">My Account</h4>
        </div>
      </div>
  </div>
  <div class="row p-5"></div>
  <div class="card">
      <form method="POST" action="{% url 'edit_my_account' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <!-- Image, Name, Role -->
          <div class="row mt-2 mb-4">
              <div class="col"><h5>{{user.account.First_Name}} {{user.account.Last_Name}}</h5></div>
              <div class="col d-flex justify-content-end">
                  <h6>Role: Administrator</h6>
              </div>
          </div>

          <!-- Old user info -->
          <div class="row">
              <!-- Username -->
              <div class="col">
                  <label for="username">Username</label><br>
                  <input type="text" id="username" name="username" value="{{user.username}}">
              </div>

              <div class="col">
              </div>
          </div>

          <!-- New password -->
          {% if error_msg %}
            <div class="col-12 alert alert-danger" role="alert" style="margin-top: 20px;">
              {{ error_msg }} 
            </div>
          {% endif %}
          <div class="row">
              <div class="col">
                  <label for="new_password">New Password</label><br>
                  <input type="password" id="new_password" name="new_password" required>
              </div>
              <div class="col">
                  <label for="reenter_new_password">Re-enter New Password</label><br>
                  <input type="password" id="reenter_new_password" name="reenter_new_password" required>
              </div>
          </div>
          <button type="button" id="toggle-password-btn">Keep old password</button>
          <div class="mb-3">
            <div class="row">
                <div class="col-md-5">
                    <label for="id_Picture" class="form-label custom-text">Picture:</label>
            <div id="image-preview">
                {% if user.account.Profile_Picture %}
                <div class="profile-image"> 
                    <img src="{{ user.account.Profile_Picture.url }}" width="50">
                </div>
                {% endif %}
            </div>
            <div style="display: flex; align-items: center;" >
                <input type="file" name="profile_picture" accept="image/*" id="id_Picture" class="form-control" style="flex: 1; margin-right: 8px;"> <!-- Added margin-right -->
                <button type="button" id="remove-image" {% if not user.account.Profile_Picture %}style="display: none;"{% endif %} class="btn btn-outline-danger">Remove Image</button>
            </div>
            <input type="hidden" name="removed_profile_picture" id="remove-profile-picture" value='Not'>
                    <div class="col-md-3"></div> <!-- Invisible column -->
                    <div class="col-md-3"></div> <!-- Invisible column -->
                </div>
            </div>

          <!-- Cancel & Save button row -->
          <div class="row">
            <div class="col">
              <a class="btn btn-danger btn-edit" onclick="showCancelWarningModal()">Cancel</a>
            </div>
            <div class="col-md-auto">
              <button type="submit" class="btn btn-primary btn-edit" onclick="validateForm()">Submit</button>
            </div>
          </div>
      </form>
  </div>

  <script>
    // Function to display the cancel warning modal
    function showCancelWarningModal() {
            var myModal = new bootstrap.Modal(document.getElementById('cancelWarningModal'));
            myModal.show();
        }

    // Function to direct back to current inventoRY
    function cancelForm() {
        window.location.href = "{% url 'my_account' %}";
    }

    // Function to validate form inputs
    function validateForm() {
        var inputs = document.querySelectorAll('input[required]');
        var isValid = true;

        inputs.forEach(function(input) {
          input.classList.remove('invalid-input'); // Remove any existing invalid-input class
          if (!input.value.trim()) {
            isValid = false;
            input.classList.add('invalid-input'); // Add red outline for empty fields
          }
        });

        if (isValid) {
          // All required fields are filled, prompt for confirmation
          var confirmation = confirm('Are you sure you want to save a new account?');
          if (confirmation) {
            // If user confirms, proceed with saving
            return true;
          } else {
            // If user cancels confirmation, prevent form submission
            return false;
          }
        } else {
          // There are blank fields, do not proceed and prevent form submission
          return false;
        }
      }
      document.addEventListener("DOMContentLoaded", function() {
          const pictureInput = document.getElementById("id_Picture");
          const imagePreview = document.getElementById("image-preview");
          const removeImageButton = document.getElementById("remove-image");
          const imageRemoved = document.getElementById("remove-profile-picture");

          // Function to update the image preview
          function updatePreview() {
              const file = pictureInput.files[0];
              if (file) {
                  const reader = new FileReader();
                  reader.onload = function(event) {
                      const image = new Image();
                      image.src = event.target.result;
                      image.width = 50;
                      imagePreview.innerHTML = '';
                      imagePreview.appendChild(image);
                      imageRemoved.value = "Not";
                      removeImageButton.style.display = "inline-block"; // Show the "Remove Image" button
                  };
                  reader.readAsDataURL(file);
              } else {
                  imagePreview.innerHTML = '';
              }
          }

          // Event listener for input change
          pictureInput.addEventListener("change", updatePreview);

          // Event listener for remove image button
          removeImageButton.addEventListener("click", function() {
              pictureInput.value = null; // Clear the input field
              removeImageButton.style.display = "none"; // Hide the "Remove Image" button
              imageRemoved.value = "removed";
              updatePreview(); // Update the preview to remove the image
          });
      });
      
      document.addEventListener("DOMContentLoaded", function() {
        const newPasswordInput = document.getElementById("new_password");
        const reenterNewPasswordInput = document.getElementById("reenter_new_password");
        const togglePasswordBtn = document.getElementById("toggle-password-btn");

        // Function to fill password fields with a static string and make them non-required
        function togglePasswordFields() {
            // Fill password fields with a static string
            newPasswordInput.value = "no need password";
            reenterNewPasswordInput.value = "no need password";

            // Make password fields non-required
            newPasswordInput.required = false;
            reenterNewPasswordInput.required = false;
        }

        // Event listener for button click
        togglePasswordBtn.addEventListener("click", togglePasswordFields);
    });

    </script>
</body>

<div class="modal fade" id="cancelWarningModal" tabindex="-1" aria-labelledby="cancelWarningModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="cancelWarningModalLabel">Warning</h5>
          </div>
          <div class="modal-body">
            Exit form? Any changes you have made may not be saved.
          </div>
          <div class="modal-footer">
            <div class="col">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Back</button>
            </div>
            <button type="button" class="btn btn-danger" onclick="cancelForm()">Exit Anyways</button>
          </div>
      </div>
  </div>
</div>
{% endblock %}